[[constraint]]
  version = "1.0.0"
  name = "github.com/articulate/oktasdk-go"

[[constraint]]
  version = "0.11.7"
  name = "github.com/hashicorp/terraform"

[prune]
  go-tests = true
  unused-packages = true
